// examples/md.vue
<template>
  <span class="markdown__nodes">
    <span
      v-for="(node, index) in nodes"
      :key="index"
      class="markdown__node-item"
    >
      <code v-if="mdTypes.INLINE_CODE === node.type">{{ node.value }}</code>
      <em v-else-if="mdTypes.EMPHASIS === node.type" class="markdown__em">
        <MDnode :nodes="node.children"></MDnode
      ></em>
      <strong v-else-if="mdTypes.STRONG === node.type" class="markdown__strong">
        <MDnode :nodes="node.children"></MDnode
      ></strong>
      <a
        v-else-if="mdTypes.LINK === node.type"
        :href="node.url"
        target="_blank"
        rel="noreferrer"
        class="markdown__link"
      >
        <MDnode :nodes="node.children"></MDnode
      ></a>
      <span v-else-if="mdTypes.TEXT === node.type">{{ node.value }}</span>
      <span v-else>⚠️ no handling - {{ node.type }}</span>
    </span>
  </span>
</template>

<script>
import { mdTypes } from 'mdast-util-from-span-markdown'

export default {
  name: 'MDnode',
  props: {
    nodes: {
      type: Array,
      default: () => {
        return []
      },
    },
  },
  data() {
    return {
      mdTypes,
    }
  },
}
</script>

// examples/md.tsx
import React from "react";
import "./styles.css";

import fromMarkdown, { mdTypes, mdToken } from "mdast-util-from-span-markdown";

export type markdownProps = {
  text: string;
};

const obj2jsx = (token: mdToken, key: number) => {
  switch (token.type) {
    case mdTypes.INLINE_CODE:
      return <code key={key}>{token.value}</code>;
      break;
    case mdTypes.EMPHASIS:
    case mdTypes.STRONG:
      return (
        <em key={key}>
          {token.children.map((item, index) => obj2jsx(item, index))}
        </em>
      );
      break;
    case mdTypes.LINK:
      return (
        <a key={key} href={token.url} target="_blank" rel="noreferrer">
          {token?.children.map((item, index) => obj2jsx(item, index))}
        </a>
      );
      break;
    case mdTypes.TEXT:
      return (
        <span className="markdown__text" key={key}>
          {token.value}
        </span>
      );
      break;
    default:
      return <span>⚠️ no handling</span>;
      break;
  }
};

const Markdown = ({ text }: markdownProps) => {
  const tokens = fromMarkdown(text);
  return (
    <span className="markdown">
      {tokens && tokens.map((token, index) => obj2jsx(token, index))}
    </span>
  );
};
export default Markdown;
